### ISSUE TITLE
[Minor scheme question] Futuristic7 scheme missing startup sound; is this intentional?

### ISSUE THREAD

**Issue by TheInsane101** [ORelio/Sound-Manager-Schemes#12] opened 2024-08-20 16:37 UTC
I see that the Futuristic7 sound scheme has a shutdown sound but no startup sound. I see the author field says it was slightly edited by ORelio, so I'd like to know is this intentional (is there no custom startup sound for this theme) or is it a mistake?

https://github.com/user-attachments/assets/f2311cfc-adb4-4a24-977a-4841c945c9dd

**Comment by TheInsane101** [comment] 2024-08-20 18:19
Oh, I see you added it from Stardock's Sound_Packager_ library! Nice!

**Comment by ORelio** [comment] 2024-08-22 09:56
Yes, you can load soundpack files using SoundManager since v3.2.0.
Closing this thread as answered, feel free to ask if you have more questions.

**Closed by ORelio** 2024-08-22 09:56 UTC

**Comment by ORelio** [comment] 2024-09-23 11:07
Hi,

Just to let you know that Futuristic7 II includes a startup sound.
https://www.wincustomize.com/explore/sound_schemes/290/
Included it in the repository, and added the startup sound to the original version.

> I'm not 100% sure what I edited but usually it's removing unnecessary silence in sound file or adjusting loudness.

So for Futuristic7 (first revision) the "slightly edited by ORelio" mention is due to the following changes:
* Reduced volume for `Navigate.wav` (navigate in file browser and internet explorer)
* `Question.wav` was the same as `Warning.wav`: replaced it with `alert.wav` (unused) from Futuristic7
* Startup sound was missing so backported `Startup.wav` from Futuristic7 II

I'd rather not credit myself for such subtle changes, but this is for not blaming the author in case one of the changes is seen as a regression.
